M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu24.04.1} date 2025-02-27T11:00:24-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-27T11:00:24-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.0548Y-2.5658
X2.355Y-2.5658
M30
